### ISSUE TITLE
[CLIENT] [ERROR] Big integer literals are not available in the configured target environment 

### ISSUE THREAD

**Issue by z7pz** [itchatapp/itchat.js#3]
✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/.pnpm/@itchatapp+utils@1.0.4/node_modules/@itchatapp/utils/esm/src/Permissions.js:26:29:
      26 │         INVITE_OTHERS: 1n << 14n,
         ╵                              ~~~

**Comment by abdulrahman1s** [comment]
Just bump up the target to newer version that supports bigints

**Comment by z7pz** [comment]
i tired es2020 and esnext and i got  the same issue @abdulrahman1s

**Comment by z7pz** [comment]
can you try it yourself it's on preact (vite)
those are my config

# vite.config.ts
```ts
import { defineConfig } from "vite";


import preact from "@preact/preset-vite";
import sassDts from "vite-plugin-sass-dts";

export default defineConfig({
  plugins: [
    preact(),
    sassDts({
      enabledMode: ["development"],
    }),
  ],
  build: {
    target: "ESNext",
  },
  esbuild: {
    logOverride: { "this-is-undefined-in-esm": "silent" },
  },
});
```

# tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "Fragment",
    "noEmit": true,
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "baseUrl": "./",
    "paths": {
      "react": ["./node_modules/preact/compat"],
      "react-dom": ["./node_modules/preact/compat"]
    },
    "skipLibCheck": true
  },
  "include": ["src/**/*"]
}
```

**Comment by abdulrahman1s** [comment]
override `esbuild.target` to `es2020`
and bump up safari version to `14` instead of `13`

Read [Bigint browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt#browser_compatibility) for more info

**Comment by z7pz** [comment]
anyway i fixed it by adding
```json
  "optimizeDeps": {
    "esbuildOptions": {
      "target": "es2020"
    }
  },
  ```
  to vite config

**Comment by z7pz** [comment]
thank you
